// Code generated by "stringer -type=iterations"; DO NOT EDIT.

package day14

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[three-3]
	_ = x[billion-1000000000]
	_ = x[onepercent-10000000]
}

const (
	_iterations_name_0 = "three"
	_iterations_name_1 = "onepercent"
	_iterations_name_2 = "billion"
)

func (i iterations) String() string {
	switch {
	case i == 3:
		return _iterations_name_0
	case i == 10000000:
		return _iterations_name_1
	case i == 1000000000:
		return _iterations_name_2
	default:
		return "iterations(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
