// Code generated by "stringer -type=Card"; DO NOT EDIT.

package day7

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T-10]
	_ = x[J-11]
	_ = x[Q-12]
	_ = x[K-13]
	_ = x[A-14]
}

const _Card_name = "TJQKA"

var _Card_index = [...]uint8{0, 1, 2, 3, 4, 5}

func (i Card) String() string {
	i -= 10
	if i < 0 || i >= Card(len(_Card_index)-1) {
		return strconv.FormatInt(int64(i+10), 10)
	}
	return _Card_name[_Card_index[i]:_Card_index[i+1]]
}
